<?php
get_header();
//get_template_part('partials/top-menu');
//get_template_part('partials/main_titr');
//get_template_part('partials/main_slider');
//get_template_part('partials/search');
//get_template_part('partials/services');
//get_template_part('partials/intro');
//get_template_part('partials/work-featured');
//get_template_part('partials/counter');
//get_template_part('partials/blog');
//get_template_part('partials/subscribe');
//get_template_part('partials/pricing');
get_template_part('partials/footer_content');
get_footer();